### ISSUE TITLE
Bug: text color on light and dark values unreadable

### ISSUE THREAD

**Issue by anoatflake** [13ruceYu/hsl-preview#1]
With some values the text color has a too low contrast to be readable
![image](https://github.com/user-attachments/assets/1bd73a21-b6e3-4c43-9099-9d9858fb0d79)

This has to do with the way the text color is currently determined and needs a more complex check.

PS: Are you accepting contributors on this repo? I would be interested in fixing this myself

**Comment by 13ruceYu** [comment]
Sure, feel free to send a pull request!❤️
