### ISSUE TITLE
Support tailwindcss language

### ISSUE THREAD

**Issue by claudiorivera** [13ruceYu/hsl-preview#4]
Currently, when opening a `.css` file that [has a configured language set to `tailwindcss`](https://github.com/tailwindlabs/tailwindcss-intellisense?tab=readme-ov-file#filesassociations), the extension is not enabled.

It would be great if the extension was enabled on Tailwind CSS files.

**Comment by 13ruceYu** [comment]
I'm not quite sure about your use case. Could you give me a simple example with a screenshot :D

**Comment by claudiorivera** [comment]
Same file in two different modes:

Language mode: `css`
<img width="1728" alt="css" src="https://github.com/user-attachments/assets/ac82ed10-8492-48a4-9734-8a7a44a64e70">

Language mode: `tailwindcss`
<img width="1728" alt="tailwindcss" src="https://github.com/user-attachments/assets/149c5a6d-1cf1-456f-9e87-ae8f008f6c64">

I've never authored a VS Code extension, but I wonder if it's a [`one-line change here`](https://github.com/13ruceYu/hsl-preview/blob/59af6302c9b12f8b0baa437011e24b07e0093a28/src/extension.ts#L13)?

**Comment by 13ruceYu** [comment]
I understand, I'll update it ASAP.
